FROM n8nio/n8n:latest

# Set environment variables
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV GENERIC_TIMEZONE=Asia/Kolkata
ENV N8N_SECURE_COOKIE=false

# Expose the n8n port
EXPOSE 5678

# Start n8n
CMD ["n8n", "start"]
